services:
  mongodb:
    image: mongodb/mongodb-enterprise-server:8.0.26-ubi9-slim
    container_name: kartagalaxy-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=verysecretlocalpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - kartagalaxy-network

volumes:
  mongodb-data:

networks:
  kartagalaxy-network:
    external: true