services:
  postgres:
    image: postgres:14.24-alpine3.23
    container_name: esplanade-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=verysecretlocalpassword
    ports:
      - "2000:5432"
    volumes:
      - postgres-data:/data/db
    networks:
      - esplanade-network

volumes:
  postgres-data:

networks:
  esplanade-network:
    external: true