server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:2000/esplanade}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:verysecretlocalpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:2000/esplanade}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:verysecretlocalpassword}
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:minio-server-local}
  port: ${MINIO_LOCAL_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:root}
  secret-key: ${MINIO_SECRET_KEY:verysecretlocalpassword}
  bucket: ${MINIO_BUCKET:esplanade}
  secure: ${MINIO_SECURE:false}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:2001/esplanade}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:verysecretlocalpassword}
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:localhost}
  port: ${MINIO_LOCAL_PORT:9002}
  access-key: ${MINIO_ACCESS_KEY:neverdiscloseyoursecretsinconfigfiles}
  secret-key: ${MINIO_SECRET_KEY:neverdiscloseyoursecretsinconfigfiles}
  bucket: ${MINIO_BUCKET:esplanade}
  secure: ${MINIO_SECURE:false}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:2000/esplanade}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:verysecretlocalpassword}
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:localhost}
  port: ${MINIO_LOCAL_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:neverdiscloseyoursecretsinconfigfiles}
  secret-key: ${MINIO_SECRET_KEY:neverdiscloseyoursecretsinconfigfiles}
  bucket: ${MINIO_BUCKET:esplanade}
  secure: ${MINIO_SECURE:true}